more stuff

diff --git a/.github/workflows/changeset.yml b/.github/workflows/changeset.yml
--- a/.github/workflows/changeset.yml
+++ b/.github/workflows/changeset.yml
@@ -2,7 +2,7 @@ name: Changeset
 
 on:
   pull_request:
-    branches: [ master ]
+    branches: [master]
   workflow_dispatch:
 
 jobs:
@@ -19,11 +19,18 @@ jobs:
       - name: Fetch master
         run: git fetch origin master:master
 
+      - name: Install pnpm
+        uses: pnpm/action-setup@v4
+
       - name: Install Node.js
         uses: actions/setup-node@v4
         with:
           node-version: 24
+          cache: "pnpm"
+
+      - name: Install dependencies
+        run: pnpm install --frozen-lockfile
 
       - name: Check for changeset
         run: |
-          npx @changesets/cli status --since=master || (echo "::error title=Changeset required::A changeset is required for this contribution. Please refer to [CONTRIBUTING.md](CONTRIBUTING.md) for instructions on how to add one."; exit 1)
+          pnpm exec changeset status --since=master || (echo "::error title=Changeset required::A changeset is required for this contribution. Please refer to [CONTRIBUTING.md](CONTRIBUTING.md) for instructions on how to add one."; exit 1)
